/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 satla2.gltf 
Author: Duane's Mind (https://sketchfab.com/duanesmind)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/satellite-comms-4be56951da39429a963ee12140bbff57
Title: Satellite Comms
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export  default function Satla2(props) {
  const { nodes, materials } = useGLTF('/satla2.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.759}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <mesh geometry={nodes.Base_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Arm_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Dish_Material_0.geometry} material={materials.Material} position={[0, 471.132, -1008.182]} rotation={[0.874, 0, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/satla2.gltf')
